config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
            controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
            passwords: 'users/passwords'}

  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
    end
  end

  resources :groups, only: [:index, :show, :create, :new], path: '/categories'
  resources :user_transactions, only: [:new, :create], path: '/transactions'

  post '/navbar/welcome', to: 'welcome#navbar'
  post '/navbar/logged', to: 'users#navbar'
  root to: 'welcome#index'
end

app/controllers/user_transactions_controller.rb
class UserTransactionsController < ApplicationController
  load_and_authorize_resource :user

  def new
    render_nav(true)
    @user_transaction = UserTransaction.new
    @transaction_group = TransactionGroup.new
    respond_to do |format|
      format.js { render 'user_transactions/js/new.js.erb' }
      format.html
    end
  end

  def create
    render_nav(true)
    @user_transaction = UserTransaction.new(transaction_params)
    @transaction_group = TransactionGroup.new(transaction_group_params)

    if @user_transaction.save
      @transaction_group.user_transaction_id = @user_transaction.id
      @transaction_group.save
      redirect_to group_path(@transaction_group.group_id), format: 'js'
      nil
    else
      respond_to do |format|
        format.js { render 'user_transactions/js/new.js.erb' }
        format.html
      end
    end
  end

  protected

  def transaction_params
    params.require(:user_transaction).permit(:name, :amount, :author_id)
  end

  def transaction_group_params
    params.require(:user_transaction).permit(:group_id)
  end
end

app/helpers/user_transactions_helper.rb
module UserTransactionsHelper
  def group_list
    {
      groups: @user.groups,
      selected: params[:group_id]
    }
  end
end

app/views/user_transactions/_add_transaction.html.erb
<div class="add-transaction-container d-flex flex-column pt-100p">
  <div class="d-flex flex-column">
    <%= render partial: 'errors/form_errors', locals: { model: @user_transaction} %>
    <%= form_with url: user_transactions_path, scope: @user_transaction, local: false, id: 'add-transaction', class: 'd-flex flex-column background-color-1' do |f| %>
        <%= f.hidden_field :author_id, value: @user.id %>
        <div class="field input-border">
          <div class="select-label">
            <%= f.label 'Choose a group: ', class: 'fc-5'%><br />
          </div>
          <%= f.collection_select :group_id, group_list[:groups], :id, :name, selected: group_list[:selected], class: 'default-input w-100 fc-5' %>
        </div>
        <div class="field input-border">
          <%= f.text_field :name, placeholder: 'Transaction info', autofocus: true, class: 'default-input w-100', value: '' %>
        </div>
        <div class="field">
          <%= f.number_field :amount, placeholder: 'Transaction value', autofocus: true, class: 'default-input w-100' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user_transactions/_transaction_card.html.erb
<div class='category-container d-flex mt-1'>
  <img class="group-icon mr-1" src='<%= @group.icon %>' alt='category-icon'/>
  <div class='d-flex flex-column w-100'>
      <div class='d-flex justify-between'>
        <p class="fc-1">
          <%= transaction.name %>
        </p>
        <p class="fc-1">
          $ <%= transaction.amount %>
        </p>
      </div>
      <p class="mt-auto mb-1 fc-1">
        Created: <%= transaction.created_at.strftime('%d %b %Y') %>
      </p>
  </div>
</div>

app/views/user_transactions/create.html.erb
<% new_transaction_nav_options %>

<%= render partial: 'user_transactions/add_transaction' %>

app/views/user_transactions/new.html.erb
<% new_transaction_nav_options %>
<% if Group.where(user_id: @user.id).empty? %>
  <% @path = root_path %>
  <div class="page-container d-flex flex-column vh-100">
    <div class="d-flex flex-column align-items-center justify-around h-100">
      <h1 class="fc-3 text-center">
        Error: You have not added any groups yet!
      </h1>
    </div>
  </div>
<% else %>
  <div class="add-transaction-container d-flex flex-column pt-100p">
    <div class="d-flex flex-column">
      <%= form_with url: user_transactions_path, scope: @user_transaction, remote: true, id: 'add-transaction', class: 'd-flex flex-column background-color-1' do |f| %>
          <%= render partial: 'errors/form_errors', locals: { model: @user_transaction} %>
          <%= f.hidden_field :author_id, value: @user.id %>
          <div class="field input-border">
            <div class="select-label">
              <%= f.label 'Choose a group: ', class: 'fc-5'%><br />
            </div>
            <%= f.collection_select :group_id, group_list[:groups], :id, :name, selected: group_list[:selected], class: 'default-input w-100 fc-5' %>
          </div>
          <div class="field input-border">
            <%= f.text_field :name, placeholder: 'Transaction info', autofocus: true, class: 'default-input w-100', value: '' %>
          </div>
          <div class="field">
            <%= f.number_field :amount, placeholder: 'Transaction value', autofocus: true, class: 'default-input w-100' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>