config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
            controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
            passwords: 'users/passwords'}

  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'welcome#index', as: :unauthenticated_root
    end
  end

  resources :groups, only: [:index, :show, :create, :new], path: '/categories'
  resources :user_transactions, only: [:new, :create], path: '/transactions'

  post '/navbar/welcome', to: 'welcome#navbar'
  post '/navbar/logged', to: 'users#navbar'
  root to: 'welcome#index'
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, :icon, presence: true
  belongs_to :user
  has_many :transaction_groups
  has_many :user_transactions, through: :transaction_groups, dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource :user

  def index
    render_nav(true)
    @groups = Group.where(user_id: @user.id).includes(:user_transactions, transaction_groups: [:user_transaction])
    respond_to do |format|
      format.js { render 'groups/js/index.js.erb' }
      format.html
    end
  end

  def show
    render_nav(true)
    @group = Group.find_by_id(params[:id])
    @user_transactions = @group.user_transactions
    respond_to do |format|
      format.js { render 'groups/js/show.js.erb' }
      format.html
    end
  end

  def new
    render_nav(true)
    @groups = @user.groups
    @group = Group.new
    respond_to do |format|
      format.js { render 'groups/js/new.js.erb' }
      format.html
    end
  end

  def create
    @group = Group.new(group_params)
    render_nav(true)
    if @group.save
      redirect_to groups_path, format: 'js'
      nil
    else
      respond_to do |format|
        format.html
      end
    end
  end

  protected

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_add_category.html.erb
<div class="page-container d-flex flex-column pt-100p">
  <div class="d-flex flex-column">
    <%= render partial: 'errors/form_errors', locals: { model: @group} %>
    <%= form_with url: groups_path, scope: @group, remote: true, id: 'add-category', class: 'd-flex flex-column background-color-1' do |f| %>
      <%= f.hidden_field :user_id, value: @user.id %>

      <div class="field input-border">
        <%= f.text_field :name, placeholder:'Group name' ,autofocus: true, class: 'default-input w-100' %>
      </div>

      <div class="field">
        <%= f.text_field :icon, placeholder: 'Image Url', autofocus: true, class: 'default-input w-100' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/groups/_group_card.html.erb
<%= link_to group_path(group.id), class: 'default-link' do %>
  <div class='category-container d-flex mt-1'>
    <img class="group-icon mr-1" src='<%= group.icon %>' alt='category-icon'/>
    <div class='d-flex flex-column w-100'>
        <div class='d-flex justify-between'>
          <p class="fc-1">
            <%= group.name %>
          </p>
          <p class="fc-1">
            Transactions: <%= group.user_transactions.length %>
          </p>
        </div>
        <p class="mt-auto mb-1 fc-1">
          Created: <%= group.created_at.strftime('%d %b %Y') %>
        </p>
    </div>
  </div>
<% end %>

app/views/groups/create.html.erb
<% new_group_nav_options %>

<%= render partial: 'groups/add_category' %>

app/views/groups/index.html.erb
<% index_group_navbar_options %>

<div class="page-container d-flex flex-column">
  <% if @groups.empty? %>
    <p>
      You have not added any category yet! Try adding one below.
    </p>
  <% else %>
    <% @groups.each do |group| %>
      <%= render partial:'groups/group_card', locals: { group: group } %>
    <% end %>
  <% end %>
  <div class="p-1 btn-color-3 mt-50p w-100">
    <%= button_to new_group_path, method: :get, remote: true, class: "default-btn-1 fc-2 w-100", id: 'nav-menu' do %>
      Add Category
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<% new_group_nav_options %>

<%= render partial: 'groups/add_category' %>

app/views/groups/show.html.erb
<% show_group_nav_options %>

<div class="user-transaction-container d-flex flex-column">
  <% if @user_transactions.empty? %>
    <p>
      You have not added any transaction for this group yet! Try adding one below.
    </p>
  <% else %>
    <% @user_transactions.each do |transaction| %>
      <%= render partial:'user_transactions/transaction_card', locals: { transaction: transaction } %>
    <% end %>
  <% end %>
  <div class="p-1 btn-color-3 mt-50p w-100">
    <%= button_to new_user_transaction_path, params: { group_id: @group.id }, method: :get, class: "default-btn-1 fc-2 w-100", id: 'nav-menu' do %>
      Add Transaction
    <% end %>
  </div>
</div>